### ISSUE TITLE
Packing in item_sort_list/resolver when trying to parse time

### ISSUE THREAD

**Issue by caemor** [Futsch1/image-sieve#36]
Image Sieve panics when I try to add my image folders in the following line:
https://github.com/Futsch1/image-sieve/blob/0fb9d7eaee31b16c2727f0ce94c030fbaedf3345/src/item_sort_list/resolvers.rs#L99-L101

The time information seems to be stored slightly different than what the parser expects: YYYY:MM:DD HH:MM:SS (2021:09:26 18:22:29)

The crash message with RUST_BACKTRACE=1:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(OutOfRange)', /home/caemor/.cargo/registry/src/github.com-1ecc6299db9ec823/image_sieve-0.5.2/src/item_sort_list/resolvers.rs:101:34
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: <image_sieve::item_sort_list::resolvers::ExifResolver as image_sieve::item_sort_list::item_traits::PropertyResolver>::get_timestamp
   4: image_sieve::item_sort_list::file_item::FileItem::new
   5: image_sieve::item_sort_list::item_list::ItemList::check_and_add
   6: image_sieve::synchronize::synchronize_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/caemor/.cargo/registry/src/github.com-1ecc6299db9ec823/image_sieve-0.5.2/src/main_window.rs:145:47
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: image_sieve::main_window::MainWindow::run
   4: image_sieve::main
```

**Comment by Futsch1** [comment]
Fix was committed, will be fixed in next release.

**Comment by caemor** [comment]
Thanks!
